name: flutter_alice_dio
description: "A lightweight version of Alice for Dio, designed for simple logging in Flutter."
version: 1.0.2
homepage: https://github.com/daturit/flutter_alice_dio

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.6.0
  overlay_support: ^2.1.0
  share_plus: ^9.0.0
  rxdart: ^0.27.1